# Noupe-local/docker-compose.yml

services:
  # Nginx 作为反向代理和负载均衡器
  nginx:
    image: nginx:latest
    container_name: noupe-2api-nginx
    restart: always
    ports:
      # 将宿主机的 8080 端口映射到 Nginx 的 80 端口
      # 你可以通过修改 .env 文件中的 NGINX_PORT 变量来更改宿主机端口
      - "${NGINX_PORT:-8080}:80"
    volumes:
      # 将本地的 nginx.conf 挂载到容器中，覆盖默认配置
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      # 确保后端服务先启动
      - app
    networks:
      - noupe-net

  # 后端 API 服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noupe-2api-app
    restart: unless-stopped
    # 不直接对外暴露端口，所有流量通过 Nginx
    env_file:
      - .env
    networks:
      - noupe-net

networks:
  noupe-net:
    driver: bridge
